<MainWidget>: 
  
      cols: 2  
      rows: 2
      padding: [12, 12, 12, 12]
      spacing: [20,20]
      #row_force_default: True
      #row_default_height: 40
            
      Button:         
            text: 'Hello 1'
            background_normal: ''
            background_color: [1,0,0,1]
      Button: 
            text: 'World 1'
      Button: 
            text: 'Hello 2'
      Button:         
            text: 'World 2'